[libraries]
androidx-core = "androidx.core:core-ktx:1.9.0"
androidx-lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.0-alpha02"

# compose
## bom
androidx-compose-bom = "androidx.compose:compose-bom:2023.01.00"
androidx-compose-mateiral3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
## other
androidx-activity-compose = "androidx.activity:activity-compose:1.6.1"
## androidTestImpl
android-test-androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
## debugImpl
debug-androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
debug-androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

# androidTestImpl
android-test-androidx-test-ext = "androidx.test.ext:junit:1.1.3"
android-test-androidx-test-espresso ="androidx.test.espresso:espresso-core:3.4.0"
# testImpl
test-junit = "junit:junit:4.13.2"

[bundles]
base = [
    "androidx-core",
    "androidx-lifecycle",
]
compose = [
    "androidx-compose-mateiral3",
    "androidx-compose-ui-tooling-preview",
    "androidx-activity-compose",
]
androidtest = [
    "android-test-androidx-compose-ui-test-junit4",
    "android-test-androidx-test-ext",
    "android-test-androidx-test-espresso",
]
debug = [
    "debug-androidx-compose-ui-tooling",
    "debug-androidx-compose-ui-test-manifest",
]
test = [
    "test-junit",
]
